sudo: required

language: go

services:
  - docker

go:
  - 1.9.x

# install emqttd docker
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y curl unzip
  - curl -fsSL http://emqtt.com/static/brokers/emqttd-docker-v2.3.1.zip -o emqttd-docker-v2.3.1.zip
  - unzip emqttd-docker-v2.3.1.zip
  - docker load < emqttd-docker-v2.3.1

before_script:
  - docker run -d --name emq -p 1883:1883 -p 8083:8083 -p 8883:8883 -p 8084:8084 -p 18083:18083 emqttd-docker-v2.3.1
  - sleep 15

script:
  - make test
